Git Native Client Option
bobg/modver pull request #6
Opened 2022-10-04 18:29 UTC by navid-public

add option to allow modver to use the native git shell client versus go-git

This is because `go-git` does not provide the option to skip fetching a remote even when cloning a repository from the local filesystem. This can cause issue when `git fetch` is not available via eith `https` or `ssh`.

2022-10-04 18:56 UTC, bobg requested changes

2022-10-04 18:56 UTC, bobg commented on go.mod
> +module github.com/navid-public/modver/v2
🤔

2022-10-04 18:56 UTC, bobg commented on compare.go
> +		return errors.Wrapf(err, "in git checkout %s", rev)
The rest of this repo uses the `fmt.Errorf("...: %w", ..., err)` pattern. Please stick with that instead of introducing a dependency on `github.com/pkg/errors`.

2022-10-04 18:56 UTC, bobg commented on cmd/modver/modver.go
> +	"github.com/navid-public/modver/v2"
🤔

2022-10-04 18:56 UTC, bobg commented on compare.go
> +func CompareGit(ctx context.Context, repoURL string, local bool, olderRev, newerRev string) (Result, error) {
Ironically, this is an incompatible change to the public API that would require a major-version bump.

One way to avoid this is to attach the git option to the context object. The caller could invoke this function like this:

```go
ctx := modver.WithGit(context.Background(), "/usr/bin/git")
result, err := modver.CompareGit(ctx, ...)
```

and then down in `gitSetup` there would be something like this:

```go
if gitBinary := GetGit(ctx); gitBinary != "" {
  ...do native-git logic...
} else {
  ...do go-git logic...
}
```

This would be a minor-version upgrade to modver. (Adding new functionality in a backward-compatible way.)

2022-10-04 19:06 UTC, navid-public commented on go.mod
> +module github.com/navid-public/modver/v2
I wanted to test it and I realized I can't do it this way.

2022-10-04 19:06 UTC, navid-public commented on cmd/modver/modver.go
> +	"github.com/navid-public/modver/v2"
I wanted to test it and I realized I can't do it this way. reverted.

2022-10-04 19:07 UTC, navid-public commented on go.mod
> +module github.com/navid-public/modver/v2
I reverted this change.

2022-10-04 21:38 UTC, navid-public commented on compare.go
> +func CompareGit(ctx context.Context, repoURL string, local bool, olderRev, newerRev string) (Result, error) {
Makes sense. What's the reasoning behind using a string value of `"/usr/bin/git"` instead of using a boolean and trusting that the `git` command is available on the system path?

2022-10-04 22:05 UTC, navid-public commented on cmd/modver/modver.go
> +		ctx := context.Background()
Inline this.

2022-10-04 22:06 UTC, navid-public commented on go.mod
> +	github.com/pkg/errors v0.9.1
forgot `go mod tidy`

2022-10-04 23:31 UTC, bobg commented on compare.go
> +func CompareGit(ctx context.Context, repoURL string, local bool, olderRev, newerRev string) (Result, error) {
You sort of answered your own question: why trust? Especially when we're already requiring the caller to supply information (to wit: the desire to override go-git behavior). Asking for that information to be the name of the git-like command to invoke covers the cases where it's not named `git` or is not on `PATH` (or the user has some wrapper they like to use, or is experimenting with a development version of git, or...)

2022-10-04 23:44 UTC, bobg commented on cmd/modver/modver.go
> +		ctx := context.WithValue(context.Background(), shared.NativeGitKey, nativeGit)
Don't use a string constant as a `context.WithValue` key. It's too easy for some other package to choose the same string and collide with the string you chose.

The idiomatic approach here is to define a singleton type like:

```go
type gitKey struct{}
```

and then attach a value to the context with:

```go
ctx := context.WithValue(ctx, gitKey{}, value)
```

Nothing but `gitKey{}` is ever equal to `gitKey{}`, and if you don't export that type, your context-attached value is perfectly isolated from other packages. That's why I suggested creating `WithGit` and `GetGit` functions. You can see this approach in action at https://github.com/bobg/fab/blob/main/context.go.

2022-10-04 23:44 UTC, bobg commented on compare.go
> +func CompareGit(ctx context.Context, repoURL string, olderRev, newerRev string) (Result, error) {
Revert this (nonfunctional) change.

2022-10-04 23:44 UTC, bobg commented on shared/constants.go
> +const NativeGitKey = "nativeGit"
As discussed above, this is not the right way to do a context-value key; but also don't create a new package just to hold a constant like this.

2022-10-04 23:44 UTC, bobg commented on compare.go
> +	if useGitNative(ctx) {
Why not push this test down into `gitSetup`?

2022-10-05 21:57 UTC, bobg reviewed
Please update the usage comment at the top of cmd/modver/modver.go, and the usage error strings in `doCompare`.

2022-10-05 21:57 UTC, bobg commented on cmd/modver/modver.go
> +	flag.StringVar(&gitPath, "gitpath", "", "tells modver to use native git client at the provided path instead of go-git library (note: only works with repos on the local file system)")
Is that note really true? Why would `git clone REMOTEGITURL` not work?

2022-10-05 23:00 UTC, navid-public commented on cmd/modver/modver.go
> +	flag.StringVar(&gitPath, "gitpath", "", "tells modver to use native git client at the provided path instead of go-git library (note: only works with repos on the local file system)")
ah sorry, this is a leftover comment from another approach, will remove.

2022-10-06 18:17 UTC, bobg approved these changes
Thank you!

2022-10-06 18:17 UTC, merged